### ISSUE TITLE
Broken Links in Formal Specification section of ReadMe

### ISSUE THREAD

**Issue by NetWalker108** [IntersectMBO/cardano-ledger#3250] opened 2023-01-14 07:53 UTC
Hyperlinks for the specs of the various eras in the resource table found in the ReadMe do not point to a specification document.

**Comment by JaredCorduan** [comment] 2023-01-14 14:39
duplicate of #3196, which we are now about to fix thanks to #3245

**Closed as not planned by JaredCorduan** 2023-01-14 14:39 UTC
