### ISSUE TITLE
Support for DRep scripts

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3435] opened 2023-05-22 18:11 UTC
We allow DReps to use script credentials, but in order for this to be meaningful, we need:

* A `DRep` [script purpose](https://github.com/input-output-hk/cardano-ledger/blob/46fcd149e4c887b7102bc504cdcf66e19831d86f/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs#L371).
  * Support for the new script purpose in the redeemer pointers (specifically, in [Tag](https://github.com/input-output-hk/cardano-ledger/blob/46fcd149e4c887b7102bc504cdcf66e19831d86f/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs#L371))
* Probably new fields added to the Plutus V3 script context:
  * governance actions?
  * votes?

**Comment by lehins** [comment] 2023-07-18 23:51
Closing as duplicate of #3538 and #3533

**Closed as completed by lehins** 2023-07-18 23:51 UTC
Labels: ConwayEra
