### ISSUE TITLE
BUG: missing some MIR rewards in reward account

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#2506] opened 2021-10-02 14:02 UTC
The below stake key has 3 MIR transactions from catalyst voting, but the balance has only rewards from 2 MIRs. One such possibility is that one MIR transaction in the same epoch is overriding the other MIR transaction done in the same epoch for the same stake key. This was the case for voting rewards distributed for funds 4 and 5.

https://cardanoscan.io/stakeKey/7688fbe19486778475b00cfb36e73a69d23b6ce1bb751c1546449838?tab=instantaneousrewards

The MIRs that resulted in reward account balance currently are below 2 transactions,

https://cardanoscan.io/transaction/3bfe6128c8c3724be7db0e88d8a73d95692bbdd5ee9ae8442b2fb2739a3c3860?tab=instantaneousrewards

https://cardanoscan.io/transaction/9d34c185282ebc2433d9474d74be8101de429a39a286ecf5535ac6a5d230d8a3?tab=instantaneousrewards

The MIR that didn't add balance to the reward account is,
https://cardanoscan.io/transaction/6b8e8f149a6058c46b8324a2c5544b183f3e162e8c46b0a477f3dc41ec0d8dd8?tab=instantaneousrewards

The actual reward balance for this stake key should ideally be `1235279` lovelaces

**Comment by nc6** [comment] 2021-10-04 10:25
When MIR certs were introduced, they had only been intended for one-off, rare use cases. The principal concern was for correctness of whatever reward payouts were made; hence, the semantics for multiple instantaneous rewards was to override (since the latter would be assumed to "correct" the former).

Since the scope of what MIR certs are being used for has expanded, protocol version 5 (initial Alonzo PV) changed the semantics to instead sum rewards from successive MIR certs (and allowing for negative values to "correct" anything).

Unfortunately, the linked transactions were both submitted in epoch 285, which predated the Alonzo HF and switch to PV5 (which started in epoch 290). Hence they were processed under the _previous_ semantics, and, as suggested in the issue, the second MIR cert overrode the first one.

I'll check internally whether this was intended, and, if not, we'll work out a plan to address this.

**Comment by disassembler** [comment] 2021-10-04 12:53
We're aware of the issue and will be remedying it soon. We've had this tracked internally since the epoch change where these were paid out, but due to circumstances of hard forks, travel, etc... We haven't re-sent the rewards. In Alonzo era, MIR's are summed, but in pre-alonzo they replace. I wasn't aware of this until @JaredCorduan and I did a deep dive debug session on why all the rewards weren't lining up.

**Comment by JaredCorduan** [comment] 2021-10-05 21:50
I'm going to close this issue since the code is working as expected.

**Closed as completed by JaredCorduan** 2021-10-05 21:50 UTC

**Comment by rdlrt** [comment] 2021-10-06 03:28
> the code is working as expected.

Do you mean this should now be worked upon to fix query results retrospectively on node and dbsync?
